name: 🚧 PR Validation
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXT_DATABASE_URL: ${{ secrets.NEXT_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Corepack
        run: corepack enable
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
